/**
 * Tests for Codex session config generation.
 *
 * Tests the config-generator (TOML generation from sources)
 * and session-config (directory/file orchestration).
 */
import { describe, it, expect, beforeEach, afterEach } from 'bun:test';
import { mkdirSync, existsSync, readFileSync, rmSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import {
  generateCodexConfig,
  validateSlugForToml,
  type CodexConfigGeneratorOptions,
} from '../src/codex/config-generator.ts';
import {
  setupCodexSessionConfig,
  type SetupCodexSessionConfigOptions,
} from '../src/codex/session-config.ts';
import type { SdkMcpServerConfig } from '../src/agent/backend/types.ts';
import type { LoadedSource } from '../src/sources/types.ts';

// ============================================================
// Test helpers
// ============================================================

function createMockSource(overrides: Partial<LoadedSource['config']> & { slug: string }): LoadedSource {
  return {
    config: {
      slug: overrides.slug,
      name: overrides.name || `Test Source ${overrides.slug}`,
      type: overrides.type || 'mcp',
      enabled: overrides.enabled !== undefined ? overrides.enabled : true,
      isAuthenticated: true,
      ...overrides,
    } as any,
    guide: null,
    folderPath: `/tmp/sources/${overrides.slug}`,
    workspaceRootPath: '/tmp/workspace',
    workspaceId: 'test-workspace',
  };
}

function createStdioMcpConfig(command: string, args?: string[]): SdkMcpServerConfig {
  return { type: 'stdio', command, args };
}

function createHttpMcpConfig(url: string, headers?: Record<string, string>): SdkMcpServerConfig {
  return { type: 'http', url, headers };
}

let testDir: string;

function createTestDir(): string {
  const dir = join(tmpdir(), `codex-config-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

// ============================================================
// validateSlugForToml
// ============================================================

describe('validateSlugForToml', () => {
  it('accepts valid slugs', () => {
    expect(validateSlugForToml('my-source')).toBe('my-source');
    expect(validateSlugForToml('github')).toBe('github');
    expect(validateSlugForToml('my-api-2')).toBe('my-api-2');
    expect(validateSlugForToml('a')).toBe('a');
  });

  it('rejects slugs with dots (TOML nested table injection)', () => {
    expect(() => validateSlugForToml('my.source')).toThrow('dangerous characters');
  });

  it('rejects slugs with brackets (TOML syntax injection)', () => {
    expect(() => validateSlugForToml('my[source]')).toThrow('dangerous characters');
  });

  it('rejects slugs with quotes', () => {
    expect(() => validateSlugForToml('my"source')).toThrow('dangerous characters');
  });

  it('rejects slugs with spaces', () => {
    expect(() => validateSlugForToml('my source')).toThrow('dangerous characters');
  });

  it('rejects slugs that start with hyphens', () => {
    expect(() => validateSlugForToml('-my-source')).toThrow('does not match expected pattern');
  });

  it('rejects slugs that end with hyphens', () => {
    expect(() => validateSlugForToml('my-source-')).toThrow('does not match expected pattern');
  });
});

// ============================================================
// generateCodexConfig
// ============================================================

describe('generateCodexConfig', () => {
  it('generates header and sandbox section with no sources', () => {
    const result = generateCodexConfig({ sources: [] });
    expect(result.toml).toContain('# Generated by Normies');
    expect(result.toml).toContain('sandbox_mode = "danger-full-access"');
    expect(result.mcpSources).toEqual([]);
    expect(result.apiSources).toEqual([]);
    expect(result.warnings).toEqual([]);
  });

  it('generates MCP server section for stdio source', () => {
    const source = createMockSource({ slug: 'my-db', type: 'mcp' });
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'my-db': createStdioMcpConfig('/usr/bin/mcp-db', ['--port', '5432']),
    };

    const result = generateCodexConfig({ sources: [source], mcpServerConfigs });

    expect(result.toml).toContain('[mcp_servers.my-db]');
    expect(result.toml).toContain('command = "/usr/bin/mcp-db"');
    expect(result.toml).toContain('args = ["--port", "5432"]');
    expect(result.mcpSources).toEqual(['my-db']);
    expect(result.warnings).toEqual([]);
  });

  it('generates MCP server section for HTTP source', () => {
    const source = createMockSource({ slug: 'remote-api', type: 'mcp' });
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'remote-api': createHttpMcpConfig('https://mcp.example.com', { 'Authorization': 'Bearer token123' }),
    };

    const result = generateCodexConfig({ sources: [source], mcpServerConfigs });

    expect(result.toml).toContain('[mcp_servers.remote-api]');
    expect(result.toml).toContain('url = "https://mcp.example.com"');
    expect(result.toml).toContain('http_headers');
    expect(result.mcpSources).toEqual(['remote-api']);
  });

  it('skips disabled sources', () => {
    const source = createMockSource({ slug: 'disabled-one', type: 'mcp', enabled: false });
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'disabled-one': createStdioMcpConfig('/usr/bin/mcp'),
    };

    const result = generateCodexConfig({ sources: [source], mcpServerConfigs });

    expect(result.toml).not.toContain('[mcp_servers.disabled-one]');
    expect(result.mcpSources).toEqual([]);
  });

  it('warns when MCP source has no server config', () => {
    const source = createMockSource({ slug: 'no-config', type: 'mcp' });

    const result = generateCodexConfig({ sources: [source], mcpServerConfigs: {} });

    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0].type).toBe('missing_server_config');
    expect(result.warnings[0].sourceSlug).toBe('no-config');
    expect(result.mcpSources).toEqual([]);
  });

  it('warns when slug validation fails', () => {
    // Create a source with a slug that passes the filter but fails TOML validation
    const source = createMockSource({ slug: 'bad.slug', type: 'mcp' });
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'bad.slug': createStdioMcpConfig('/usr/bin/mcp'),
    };

    const result = generateCodexConfig({ sources: [source], mcpServerConfigs });

    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0].type).toBe('slug_validation_failed');
  });

  it('tracks API sources and warns when bridge not configured', () => {
    const source = createMockSource({ slug: 'stripe', type: 'api' as any });

    const result = generateCodexConfig({ sources: [source] });

    expect(result.apiSources).toEqual(['stripe']);
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0].type).toBe('bridge_not_configured');
    expect(result.needsBridge).toBe(false);
  });

  it('includes bridge server section when API sources and bridge are configured', () => {
    const source = createMockSource({ slug: 'stripe', type: 'api' as any });

    const result = generateCodexConfig({
      sources: [source],
      bridgeServerPath: '/path/to/bridge.js',
      bridgeConfigPath: '/path/to/bridge-config.json',
      nodePath: '/usr/local/bin/node',
    });

    expect(result.toml).toContain('[mcp_servers.api-bridge]');
    expect(result.toml).toContain('command = "/usr/local/bin/node"');
    expect(result.needsBridge).toBe(true);
    expect(result.apiSources).toEqual(['stripe']);
    expect(result.warnings).toEqual([]);
  });

  it('includes session server section when all params provided', () => {
    const result = generateCodexConfig({
      sources: [],
      sessionServerPath: '/path/to/session-server.js',
      sessionId: 'sess-123',
      workspaceRootPath: '/workspace',
      plansFolderPath: '/workspace/sessions/sess-123/plans',
      nodePath: '/usr/bin/node',
    });

    expect(result.toml).toContain('[mcp_servers.session]');
    expect(result.toml).toContain('command = "/usr/bin/node"');
    expect(result.toml).toContain('"--session-id", "sess-123"');
  });

  it('skips session server section when params are missing', () => {
    const result = generateCodexConfig({
      sources: [],
      sessionServerPath: '/path/to/session-server.js',
      // Missing sessionId, workspaceRootPath, plansFolderPath
    });

    expect(result.toml).not.toContain('[mcp_servers.session]');
  });

  it('handles multiple MCP sources', () => {
    const sources = [
      createMockSource({ slug: 'github', type: 'mcp' }),
      createMockSource({ slug: 'linear', type: 'mcp' }),
      createMockSource({ slug: 'notion', type: 'mcp' }),
    ];
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'github': createStdioMcpConfig('/usr/bin/github-mcp'),
      'linear': createHttpMcpConfig('https://linear.mcp.dev'),
      'notion': createStdioMcpConfig('/usr/bin/notion-mcp', ['--key', 'abc']),
    };

    const result = generateCodexConfig({ sources, mcpServerConfigs });

    expect(result.mcpSources).toEqual(['github', 'linear', 'notion']);
    expect(result.toml).toContain('[mcp_servers.github]');
    expect(result.toml).toContain('[mcp_servers.linear]');
    expect(result.toml).toContain('[mcp_servers.notion]');
    expect(result.warnings).toEqual([]);
  });

  it('includes model provider section when configured', () => {
    const result = generateCodexConfig({
      sources: [],
      modelProvider: {
        id: 'openrouter',
        name: 'OpenRouter',
        baseUrl: 'https://openrouter.ai/api/v1',
        envKey: 'OPENROUTER_API_KEY',
        wireApi: 'chat',
        defaultModel: 'gpt-4',
      },
    });

    expect(result.toml).toContain('[model_providers.openrouter]');
    expect(result.toml).toContain('name = "OpenRouter"');
    expect(result.toml).toContain('base_url = "https://openrouter.ai/api/v1"');
    expect(result.toml).toContain('[profiles.openrouter]');
    expect(result.toml).toContain('model = "gpt-4"');
  });

  it('sets default timeout values', () => {
    const source = createMockSource({ slug: 'test', type: 'mcp' });
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'test': createStdioMcpConfig('/usr/bin/test'),
    };

    const result = generateCodexConfig({ sources: [source], mcpServerConfigs });

    expect(result.toml).toContain('startup_timeout_sec = 15');
    expect(result.toml).toContain('tool_timeout_sec = 120');
  });
});

// ============================================================
// setupCodexSessionConfig
// ============================================================

describe('setupCodexSessionConfig', () => {
  beforeEach(() => {
    testDir = createTestDir();
  });

  afterEach(() => {
    if (testDir && existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true });
    }
  });

  it('creates .codex-home directory and writes config.toml', () => {
    const result = setupCodexSessionConfig({
      sessionPath: testDir,
      sources: [],
      mcpServerConfigs: {},
    });

    const codexHome = join(testDir, '.codex-home');
    expect(existsSync(codexHome)).toBe(true);
    expect(existsSync(join(codexHome, 'config.toml'))).toBe(true);
    expect(result.codexHome).toBe(codexHome);
  });

  it('writes valid TOML with MCP sources', () => {
    const source = createMockSource({ slug: 'github', type: 'mcp' });
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'github': createStdioMcpConfig('/usr/bin/github-mcp', ['--token', 'abc']),
    };

    setupCodexSessionConfig({
      sessionPath: testDir,
      sources: [source],
      mcpServerConfigs,
    });

    const toml = readFileSync(join(testDir, '.codex-home', 'config.toml'), 'utf-8');
    expect(toml).toContain('[mcp_servers.github]');
    expect(toml).toContain('command = "/usr/bin/github-mcp"');
  });

  it('is safe to call multiple times (overwrites config)', () => {
    // First call with one source
    const source1 = createMockSource({ slug: 'source-a', type: 'mcp' });
    setupCodexSessionConfig({
      sessionPath: testDir,
      sources: [source1],
      mcpServerConfigs: {
        'source-a': createStdioMcpConfig('/usr/bin/a'),
      },
    });

    let toml = readFileSync(join(testDir, '.codex-home', 'config.toml'), 'utf-8');
    expect(toml).toContain('[mcp_servers.source-a]');

    // Second call with different source — should overwrite
    const source2 = createMockSource({ slug: 'source-b', type: 'mcp' });
    setupCodexSessionConfig({
      sessionPath: testDir,
      sources: [source2],
      mcpServerConfigs: {
        'source-b': createStdioMcpConfig('/usr/bin/b'),
      },
    });

    toml = readFileSync(join(testDir, '.codex-home', 'config.toml'), 'utf-8');
    expect(toml).toContain('[mcp_servers.source-b]');
    expect(toml).not.toContain('[mcp_servers.source-a]');
  });

  it('returns config result with source lists and warnings', () => {
    const source = createMockSource({ slug: 'missing-config', type: 'mcp' });

    const result = setupCodexSessionConfig({
      sessionPath: testDir,
      sources: [source],
      mcpServerConfigs: {},
    });

    expect(result.configResult.warnings).toHaveLength(1);
    expect(result.configResult.warnings[0].sourceSlug).toBe('missing-config');
  });

  it('passes session server config through to TOML', () => {
    setupCodexSessionConfig({
      sessionPath: testDir,
      sources: [],
      mcpServerConfigs: {},
      sessionServerPath: '/path/to/session-server.js',
      nodePath: '/usr/bin/node',
      sessionId: 'sess-abc',
      workspaceRootPath: '/workspace',
      plansFolderPath: '/workspace/sessions/sess-abc/plans',
    });

    const toml = readFileSync(join(testDir, '.codex-home', 'config.toml'), 'utf-8');
    expect(toml).toContain('[mcp_servers.session]');
    expect(toml).toContain('"--session-id", "sess-abc"');
  });
});
