/**
 * Tests for Codex Session Config Setup
 *
 * Verifies that setupCodexSessionConfig creates the per-session
 * .codex-home directory and writes a valid config.toml.
 */
import { describe, it, expect, beforeEach, afterEach } from 'bun:test';
import { existsSync, readFileSync, mkdirSync, rmSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { setupCodexSessionConfig } from '../session-config.ts';
import type { LoadedSource } from '../../sources/types.ts';
import type { SdkMcpServerConfig } from '../../agent/backend/types.ts';

// ============================================================
// Test Helpers
// ============================================================

let testDir: string;

function createTestDir(): string {
  const dir = join(tmpdir(), `codex-session-config-test-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

function createMockMcpSource(slug: string): LoadedSource {
  return {
    config: {
      id: `source-${slug}`,
      name: `Source ${slug}`,
      slug,
      enabled: true,
      provider: 'test',
      type: 'mcp',
      mcp: { transport: 'http', url: `https://${slug}.example.com` },
    } as LoadedSource['config'],
    guide: null,
    folderPath: '/test/source',
    workspaceRootPath: '/test/workspace',
    workspaceId: 'test-workspace',
  };
}

function createMockMcpServerConfig(url: string): SdkMcpServerConfig {
  return {
    type: 'http',
    url,
    headers: { Authorization: 'Bearer test-token' },
  };
}

// ============================================================
// Tests
// ============================================================

beforeEach(() => {
  testDir = createTestDir();
});

afterEach(() => {
  if (existsSync(testDir)) {
    rmSync(testDir, { recursive: true });
  }
});

describe('setupCodexSessionConfig', () => {
  it('should create .codex-home directory', () => {
    const sessionPath = join(testDir, 'session-123');
    mkdirSync(sessionPath, { recursive: true });

    const result = setupCodexSessionConfig({
      sessionPath,
      sources: [],
      mcpServerConfigs: {},
    });

    expect(existsSync(result.codexHome)).toBe(true);
    expect(result.codexHome).toBe(join(sessionPath, '.codex-home'));
  });

  it('should write config.toml to codex home', () => {
    const sessionPath = join(testDir, 'session-456');
    mkdirSync(sessionPath, { recursive: true });

    const result = setupCodexSessionConfig({
      sessionPath,
      sources: [],
      mcpServerConfigs: {},
    });

    const configPath = join(result.codexHome, 'config.toml');
    expect(existsSync(configPath)).toBe(true);

    const content = readFileSync(configPath, 'utf-8');
    expect(content).toContain('# Generated by Normies');
  });

  it('should include MCP source sections in config.toml', () => {
    const sessionPath = join(testDir, 'session-mcp');
    mkdirSync(sessionPath, { recursive: true });

    const source = createMockMcpSource('my-mcp');
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'my-mcp': createMockMcpServerConfig('https://my-mcp.example.com'),
    };

    const result = setupCodexSessionConfig({
      sessionPath,
      sources: [source],
      mcpServerConfigs,
    });

    const content = readFileSync(join(result.codexHome, 'config.toml'), 'utf-8');
    expect(content).toContain('[mcp_servers.my-mcp]');
    expect(content).toContain('url = "https://my-mcp.example.com"');
    expect(result.configResult.mcpSources).toContain('my-mcp');
  });

  it('should handle multiple MCP sources', () => {
    const sessionPath = join(testDir, 'session-multi');
    mkdirSync(sessionPath, { recursive: true });

    const sources = [
      createMockMcpSource('source-a'),
      createMockMcpSource('source-b'),
    ];
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'source-a': createMockMcpServerConfig('https://a.example.com'),
      'source-b': createMockMcpServerConfig('https://b.example.com'),
    };

    const result = setupCodexSessionConfig({
      sessionPath,
      sources,
      mcpServerConfigs,
    });

    const content = readFileSync(join(result.codexHome, 'config.toml'), 'utf-8');
    expect(content).toContain('[mcp_servers.source-a]');
    expect(content).toContain('[mcp_servers.source-b]');
    expect(result.configResult.mcpSources).toHaveLength(2);
  });

  it('should be idempotent (safe to call multiple times)', () => {
    const sessionPath = join(testDir, 'session-idem');
    mkdirSync(sessionPath, { recursive: true });

    const source = createMockMcpSource('repeat');
    const mcpServerConfigs: Record<string, SdkMcpServerConfig> = {
      'repeat': createMockMcpServerConfig('https://repeat.example.com'),
    };

    const opts = { sessionPath, sources: [source], mcpServerConfigs };

    // Call twice - should not throw
    const result1 = setupCodexSessionConfig(opts);
    const result2 = setupCodexSessionConfig(opts);

    expect(result1.codexHome).toBe(result2.codexHome);
    expect(existsSync(join(result2.codexHome, 'config.toml'))).toBe(true);
  });

  it('should pass through session server options', () => {
    const sessionPath = join(testDir, 'session-srv');
    mkdirSync(sessionPath, { recursive: true });

    const result = setupCodexSessionConfig({
      sessionPath,
      sources: [],
      mcpServerConfigs: {},
      sessionServerPath: '/path/to/session-server.js',
      sessionId: 'test-session-id',
      workspaceRootPath: '/test/workspace',
      plansFolderPath: '/test/workspace/sessions/test/plans',
      nodePath: '/usr/local/bin/node',
    });

    const content = readFileSync(join(result.codexHome, 'config.toml'), 'utf-8');
    expect(content).toContain('[mcp_servers.session]');
    expect(content).toContain('/path/to/session-server.js');
  });

  it('should include craft-agents-docs MCP server', () => {
    const sessionPath = join(testDir, 'session-docs');
    mkdirSync(sessionPath, { recursive: true });

    const result = setupCodexSessionConfig({
      sessionPath,
      sources: [],
      mcpServerConfigs: {},
    });

    const content = readFileSync(join(result.codexHome, 'config.toml'), 'utf-8');
    expect(content).toContain('[mcp_servers.craft-agents-docs]');
    expect(content).toContain('agents.craft.do');
  });

  it('should return config result with warnings for missing configs', () => {
    const sessionPath = join(testDir, 'session-warn');
    mkdirSync(sessionPath, { recursive: true });

    const source = createMockMcpSource('missing');

    const result = setupCodexSessionConfig({
      sessionPath,
      sources: [source],
      mcpServerConfigs: {}, // No config for 'missing'
    });

    expect(result.configResult.warnings).toHaveLength(1);
    expect(result.configResult.warnings[0]!.sourceSlug).toBe('missing');
    expect(result.configResult.warnings[0]!.type).toBe('missing_server_config');
  });
});
